### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by ivanperez-keera** [glguy/config-value#13]
Hi,

The License file says that this is MIT, but (some of) the code says that it's ISC:

https://github.com/glguy/config-value/blob/ecc184b822195808e2ce9a925d09fb7c1a849053/src/Config.hs#L6

Could you please clarify which one it is?

Tagging @fdedden for awareness.

**Comment by glguy** [comment]
ISC is intended

Fixed in 9b678c2
